"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Copy, Plus, Webhook } from "lucide-react";

const initial = [{ id: "ep_01", name: "Stripe Webhooks", url: "/api/webhooks/stripe", active: true, events: 12450 }, { id: "ep_02", name: "Shopify Orders", url: "/api/webhooks/shopify", active: true, events: 8320 }, { id: "ep_03", name: "GitHub Actions", url: "/api/webhooks/github", active: false, events: 3822 }];
export default function EndpointsPage() { const [endpoints, setEndpoints] = useState(initial); const [show, setShow] = useState(false); const [name, setName] = useState("");
  function add() { if (!name.trim()) return; const id = `ep_${Date.now().toString(36)}`; setEndpoints([{ id, name: name.trim(), url: `/api/webhooks/${id}`, active: true, events: 0 }, ...endpoints]); setName(""); setShow(false); }
  return <div className="space-y-8"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Endpoints</h1><p className="text-sm text-[var(--color-text-muted)]">Verwalte deine Empfangs- und Weiterleitungsziele.</p></div><Button onClick={() => setShow(true)}><Plus className="w-4 h-4 mr-2"/>Endpoint erstellen</Button></div>
    {show && <Card><CardContent className="p-5 flex gap-3"><input autoFocus value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === "Enter" && add()} placeholder="z. B. Stripe Webhooks" className="flex-1 rounded-md border border-[var(--color-border)] px-3 py-2 text-sm"/><Button onClick={add}>Speichern</Button><Button variant="outline" onClick={() => setShow(false)}>Abbrechen</Button></CardContent></Card>}
    <div className="grid gap-4">{endpoints.map(ep => <Card key={ep.id}><CardHeader className="flex flex-row items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-lg bg-blue-50 p-2"><Webhook className="w-5 h-5 text-[var(--color-primary)]"/></div><div><CardTitle className="text-base">{ep.name}</CardTitle><p className="font-mono text-xs text-[var(--color-text-muted)]">{ep.url}</p></div></div><button onClick={() => setEndpoints(endpoints.map(x => x.id === ep.id ? {...x, active: !x.active} : x))} className={`rounded-full px-3 py-1 text-xs font-medium ${ep.active ? "bg-green-50 text-green-700" : "bg-gray-100 text-gray-500"}`}>{ep.active ? "Aktiv" : "Pausiert"}</button></CardHeader><CardContent className="flex justify-between border-t border-[var(--color-border)] pt-4 text-sm text-[var(--color-text-muted)]"><span>{ep.events.toLocaleString("de-DE")} Events verarbeitet</span><button onClick={() => navigator.clipboard?.writeText(`${location.origin}${ep.url}`)} className="inline-flex items-center gap-1 hover:text-[var(--color-primary)]"><Copy className="w-4 h-4"/> URL kopieren</button></CardContent></Card>)}</div></div>;
}
